FROM nginx:alpine

# Remove the default config file in the container
RUN rm /etc/nginx/conf.d/default.conf

# Copy your local, clean site.conf file (located in ~/nginx_config_neutral/)
# directly into the container's configuration directory during the build
COPY ./nginx-config-files/site.conf /etc/nginx/conf.d/site.conf
