# Generated by Django 5.2 on 2026-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='chart_image',
            field=models.ImageField(default='chart_plots/clr_chart', upload_to='chart_plots/'),
        ),
    ]
