# Generated by Django 5.2 on 2025-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='date',
        ),
        migrations.AddField(
            model_name='chart',
            name='day',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='chart',
            name='hour',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='chart',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March')], default=2),
        ),
        migrations.AddField(
            model_name='chart',
            name='second',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='chart',
            name='year',
            field=models.IntegerField(default=1986),
        ),
        migrations.AlterField(
            model_name='chart',
            name='city',
            field=models.CharField(default='Ufa'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='country',
            field=models.CharField(default='Russia'),
        ),
    ]
