# Generated by Django 5.2 on 2026-01-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0002_alter_onecolorzodiacringmf_chart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='chart_image',
            field=models.ImageField(blank=True, default='chart_plots/', null=True, upload_to='chart_plots/'),
        ),
    ]
