# Generated by Django 5.2 on 2025-06-13 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0002_remove_chart_date_chart_day_chart_hour_chart_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='day',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='month',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='second',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='year',
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 9, 30, 0, 224881)),
        ),
    ]
