# Generated by Django 5.2 on 2026-01-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0003_alter_onecolorzodiacringmf_chart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='chart_image',
            field=models.ImageField(blank=True, default='chart_plots/Gaia_2026-01-04_1138000000', null=True, upload_to='chart_plots/'),
        ),
    ]
