# Generated by Django 5.2 on 2025-06-13 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0003_remove_chart_day_remove_chart_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 10, 30, 22, 386542)),
        ),
    ]
