# Generated by Django 5.2 on 2025-06-13 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0005_alter_chart_chart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 11, 27, 35, 312525)),
        ),
    ]
