# Generated by Django 5.2 on 2026-01-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0005_alter_fullchart_drawer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='chart_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
