# Generated by Django 5.2.12 on 2026-03-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0006_alter_onecolorzodiacringmf_chart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='city',
            field=models.CharField(default='Ufa', max_length=50),
        ),
        migrations.AlterField(
            model_name='chart',
            name='country',
            field=models.CharField(default='Russia', max_length=50),
        ),
        migrations.AlterField(
            model_name='chart',
            name='house_system',
            field=models.CharField(choices=[('P', 'Placidus'), ('R', 'Regiomontanus'), ('E', 'Equal'), ('Without houses', 'Without houses')], default='Without houses', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Jupiter_deg',
            field=models.CharField(default='5°37', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Jupiter_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Mars_deg',
            field=models.CharField(default='15°21', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Mars_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Mercury_deg',
            field=models.CharField(default='18°04', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Mercury_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Moon_deg',
            field=models.CharField(default='14°44', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Moon_sign',
            field=models.CharField(default='Taurus', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Neptune_deg',
            field=models.CharField(default='11°60', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Neptune_sign',
            field=models.CharField(default='Sagittarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Pluto_deg',
            field=models.CharField(default='13°40', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Pluto_sign',
            field=models.CharField(default='Libra', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Saturn_deg',
            field=models.CharField(default='15°18', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Saturn_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Sun_deg',
            field=models.CharField(default='5°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Sun_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Uranus_deg',
            field=models.CharField(default='28°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Uranus_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Venus_deg',
            field=models.CharField(default='12°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='Venus_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='asc_deg',
            field=models.CharField(default='0°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='asc_sign',
            field=models.CharField(default='Aries', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='benefits_deg',
            field=models.CharField(default='330°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='benefits_sign',
            field=models.CharField(default='Pisces', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='chart_name',
            field=models.CharField(default='Today', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='city',
            field=models.CharField(default='Ufa', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='country',
            field=models.CharField(default='Russia', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='eighth_house',
            field=models.CharField(default='Magic', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='eleventh_house',
            field=models.CharField(default='Interests', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='esoteric_deg',
            field=models.CharField(default='230°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='esoteric_sign',
            field=models.CharField(default='Sagittarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='fifth_house',
            field=models.CharField(default='Games', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='first_house',
            field=models.CharField(default='Ascendant', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='forth_house',
            field=models.CharField(default='Home', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='game_deg',
            field=models.CharField(default='120°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='game_sign',
            field=models.CharField(default='Crab', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='home_deg',
            field=models.CharField(default='90°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='home_sign',
            field=models.CharField(default='Crab', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='house_system',
            field=models.CharField(choices=[('P', 'Placidus'), ('R', 'Regiomontanus'), ('E', 'Equal'), ('Without houses', 'Without houses')], default='Without houses', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='interests_deg',
            field=models.CharField(default='290°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='interests_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='magic_deg',
            field=models.CharField(default='210°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='magic_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='mental_deg',
            field=models.CharField(default='60°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='mental_sign',
            field=models.CharField(default='Gemini', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='nineth_house',
            field=models.CharField(default='Esoteric knowledge', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='rel_deg',
            field=models.CharField(default='180°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='rel_sign',
            field=models.CharField(default='Libra', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='resource_deg',
            field=models.CharField(default='30°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='resource_sign',
            field=models.CharField(default='Taurus', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='second_house',
            field=models.CharField(default='What you have with & in you', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='seventh_house',
            field=models.CharField(default='Relationship', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='sixth_house',
            field=models.CharField(default='Work', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='status_deg',
            field=models.CharField(default='260°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='status_sign',
            field=models.CharField(default='Capricorn', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='tenth_house',
            field=models.CharField(default='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='third_house',
            field=models.CharField(default='Mentality', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='twelfth_house',
            field=models.CharField(default='Benefits', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='work_deg',
            field=models.CharField(default='150°', max_length=20),
        ),
        migrations.AlterField(
            model_name='fullchart',
            name='work_sign',
            field=models.CharField(default='Virgo', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Jupiter_deg',
            field=models.CharField(default='5°37', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Jupiter_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Mars_deg',
            field=models.CharField(default='15°21', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Mars_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Mercury_deg',
            field=models.CharField(default='18°04', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Mercury_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Moon_deg',
            field=models.CharField(default='14°44', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Moon_sign',
            field=models.CharField(default='Taurus', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Neptune_deg',
            field=models.CharField(default='11°60', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Neptune_sign',
            field=models.CharField(default='Sagittarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Pluto_deg',
            field=models.CharField(default='13°40', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Pluto_sign',
            field=models.CharField(default='Libra', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Saturn_deg',
            field=models.CharField(default='15°18', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Saturn_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Sun_deg',
            field=models.CharField(default='5°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Sun_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Uranus_deg',
            field=models.CharField(default='28°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Uranus_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Venus_deg',
            field=models.CharField(default='12°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='Venus_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='asc_deg',
            field=models.CharField(default='0°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='asc_sign',
            field=models.CharField(default='Aries', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='benefits_deg',
            field=models.CharField(default='330°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='benefits_sign',
            field=models.CharField(default='Pisces', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='chart_city',
            field=models.CharField(default='Ufa', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='chart_country',
            field=models.CharField(default='Russia', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='chart_house_system',
            field=models.CharField(choices=[('P', 'Placidus'), ('R', 'Regiomontanus'), ('E', 'Equal'), ('Without houses', 'Without houses')], default='Without houses', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='chart_name',
            field=models.CharField(default='Got the Olympic Prize', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='deg_color',
            field=models.CharField(default='#63ffd3', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='edge_color',
            field=models.CharField(default='#3dffc8', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='eighth_house',
            field=models.CharField(default='Magic', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='eleventh_house',
            field=models.CharField(default='Interests', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='esoteric_deg',
            field=models.CharField(default='230°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='esoteric_sign',
            field=models.CharField(default='Sagittarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='face_color',
            field=models.CharField(default='#300c63', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='fifth_house',
            field=models.CharField(default='Games', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='first_house',
            field=models.CharField(default='Ascendant', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='forth_house',
            field=models.CharField(default='Home', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='game_deg',
            field=models.CharField(default='120°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='game_sign',
            field=models.CharField(default='Crab', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='home_deg',
            field=models.CharField(default='90°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='home_sign',
            field=models.CharField(default='Crab', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='house_ax_color',
            field=models.CharField(default='#ffc83d', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='house_number_color',
            field=models.CharField(default='#ffc83d', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='house_track_color',
            field=models.CharField(default='#ffc83d', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='interests_deg',
            field=models.CharField(default='290°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='interests_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='magic_deg',
            field=models.CharField(default='210°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='magic_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='marker_color',
            field=models.CharField(default='#ffc83d', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='mental_deg',
            field=models.CharField(default='60°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='mental_sign',
            field=models.CharField(default='Gemini', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='nineth_house',
            field=models.CharField(default='Esoteric knowledge', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='rel_deg',
            field=models.CharField(default='180°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='rel_sign',
            field=models.CharField(default='Libra', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='resource_deg',
            field=models.CharField(default='30°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='resource_sign',
            field=models.CharField(default='Taurus', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='second_house',
            field=models.CharField(default='What you have with & in you', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='seventh_house',
            field=models.CharField(default='Relationship', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='sixth_house',
            field=models.CharField(default='Work', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='status_deg',
            field=models.CharField(default='260°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='status_sign',
            field=models.CharField(default='Capricorn', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='symbol_color',
            field=models.CharField(default='#ff3d74', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='tenth_house',
            field=models.CharField(default='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='text_color',
            field=models.CharField(default='#3dffc8', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='third_house',
            field=models.CharField(default='Mentality', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='tick_color',
            field=models.CharField(default='#63ffd3', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='twelfth_house',
            field=models.CharField(default='Benefits', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='work_deg',
            field=models.CharField(default='150°', max_length=20),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='work_sign',
            field=models.CharField(default='Virgo', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='event_city',
            field=models.CharField(default='Ufa', max_length=50),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='event_country',
            field=models.CharField(default='Russia', max_length=50),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='transit_city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='transit_country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Jupiter_deg',
            field=models.CharField(default='5°37', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Jupiter_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Mars_deg',
            field=models.CharField(default='15°21', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Mars_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Mercury_deg',
            field=models.CharField(default='18°04', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Mercury_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Moon_deg',
            field=models.CharField(default='14°44', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Moon_sign',
            field=models.CharField(default='Taurus', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Neptune_deg',
            field=models.CharField(default='11°60', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Neptune_sign',
            field=models.CharField(default='Sagittarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Pluto_deg',
            field=models.CharField(default='13°40', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Pluto_sign',
            field=models.CharField(default='Libra', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Saturn_deg',
            field=models.CharField(default='15°18', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Saturn_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Sun_deg',
            field=models.CharField(default='5°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Sun_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Uranus_deg',
            field=models.CharField(default='28°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Uranus_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Venus_deg',
            field=models.CharField(default='12°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='Venus_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='asc_deg',
            field=models.CharField(default='0°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='asc_sign',
            field=models.CharField(default='Aries', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='benefits_deg',
            field=models.CharField(default='330°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='benefits_sign',
            field=models.CharField(default='Pisces', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='eighth_house',
            field=models.CharField(default='Magic', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='eleventh_house',
            field=models.CharField(default='Interests', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='esoteric_deg',
            field=models.CharField(default='230°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='esoteric_sign',
            field=models.CharField(default='Sagittarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='ev_house_system',
            field=models.CharField(choices=[('P', 'Placidus'), ('R', 'Regiomontanus'), ('E', 'Equal'), ('Without houses', 'Without houses')], default='Without houses', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='event_city',
            field=models.CharField(default='Ufa', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='event_country',
            field=models.CharField(default='Russia', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='event_name',
            field=models.CharField(default='My birthdate', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='fifth_house',
            field=models.CharField(default='Games', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='first_house',
            field=models.CharField(default='Ascendant', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='forth_house',
            field=models.CharField(default='Home', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='game_deg',
            field=models.CharField(default='120°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='game_sign',
            field=models.CharField(default='Crab', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='home_deg',
            field=models.CharField(default='90°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='home_sign',
            field=models.CharField(default='Crab', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='interests_deg',
            field=models.CharField(default='290°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='interests_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='magic_deg',
            field=models.CharField(default='210°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='magic_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='mental_deg',
            field=models.CharField(default='60°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='mental_sign',
            field=models.CharField(default='Gemini', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='nineth_house',
            field=models.CharField(default='Esoteric knowledge', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='rel_deg',
            field=models.CharField(default='180°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='rel_sign',
            field=models.CharField(default='Libra', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='resource_deg',
            field=models.CharField(default='30°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='resource_sign',
            field=models.CharField(default='Taurus', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='second_house',
            field=models.CharField(default='What you have with & in you', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='seventh_house',
            field=models.CharField(default='Relationship', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='sixth_house',
            field=models.CharField(default='Work', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='status_deg',
            field=models.CharField(default='260°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='status_sign',
            field=models.CharField(default='Capricorn', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tenth_house',
            field=models.CharField(default='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='third_house',
            field=models.CharField(default='Mentality', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Jupiter_deg',
            field=models.CharField(default='5°37', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Jupiter_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Mars_deg',
            field=models.CharField(default='15°21', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Mars_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Mercury_deg',
            field=models.CharField(default='18°04', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Mercury_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Moon_deg',
            field=models.CharField(default='14°44', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Moon_sign',
            field=models.CharField(default='Taurus', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Neptune_deg',
            field=models.CharField(default='11°60', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Neptune_sign',
            field=models.CharField(default='Sagittarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Pluto_deg',
            field=models.CharField(default='13°40', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Pluto_sign',
            field=models.CharField(default='Libra', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Saturn_deg',
            field=models.CharField(default='15°18', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Saturn_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Sun_deg',
            field=models.CharField(default='5°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Sun_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Uranus_deg',
            field=models.CharField(default='28°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Uranus_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Venus_deg',
            field=models.CharField(default='12°05', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_Venus_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_asc_deg',
            field=models.CharField(default='0°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_asc_sign',
            field=models.CharField(default='Aries', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_benefits_deg',
            field=models.CharField(default='330°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_benefits_sign',
            field=models.CharField(default='Pisces', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_eighth_house',
            field=models.CharField(default='Magic', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_eleventh_house',
            field=models.CharField(default='Interests', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_esoteric_deg',
            field=models.CharField(default='230°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_esoteric_sign',
            field=models.CharField(default='Sagittarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_fifth_house',
            field=models.CharField(default='Games', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_first_house',
            field=models.CharField(default='Ascendant', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_forth_house',
            field=models.CharField(default='Home', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_game_deg',
            field=models.CharField(default='120°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_game_sign',
            field=models.CharField(default='Crab', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_home_deg',
            field=models.CharField(default='90°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_home_sign',
            field=models.CharField(default='Crab', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_house_system',
            field=models.CharField(choices=[('P', 'Placidus'), ('R', 'Regiomontanus'), ('E', 'Equal'), ('Without houses', 'Without houses')], default='Without houses', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_interests_deg',
            field=models.CharField(default='290°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_interests_sign',
            field=models.CharField(default='Aquarius', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_magic_deg',
            field=models.CharField(default='210°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_magic_sign',
            field=models.CharField(default='Scorpio', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_mental_deg',
            field=models.CharField(default='60°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_mental_sign',
            field=models.CharField(default='Gemini', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_nineth_house',
            field=models.CharField(default='Esoteric knowledge', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_rel_deg',
            field=models.CharField(default='180°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_rel_sign',
            field=models.CharField(default='Libra', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_resource_deg',
            field=models.CharField(default='30°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_resource_sign',
            field=models.CharField(default='Taurus', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_second_house',
            field=models.CharField(default='What you have with & in you', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_seventh_house',
            field=models.CharField(default='Relationship', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_sixth_house',
            field=models.CharField(default='Work', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_status_deg',
            field=models.CharField(default='260°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_status_sign',
            field=models.CharField(default='Capricorn', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_tenth_house',
            field=models.CharField(default='Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_third_house',
            field=models.CharField(default='Mentality', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_twelfth_house',
            field=models.CharField(default='Benefits', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_work_deg',
            field=models.CharField(default='150°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_work_sign',
            field=models.CharField(default='Virgo', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='transit_city',
            field=models.CharField(default='Los-Angeles', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='transit_country',
            field=models.CharField(default='USA', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='transit_name',
            field=models.CharField(default='My enlightenment day', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='twelfth_house',
            field=models.CharField(default='Benefits', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='work_deg',
            field=models.CharField(default='150°', max_length=20),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='work_sign',
            field=models.CharField(default='Virgo', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='chart_city',
            field=models.CharField(default='Ufa', max_length=500),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='chart_country',
            field=models.CharField(default='Russia', max_length=50),
        ),
    ]
