# Generated by Django 5.2 on 2025-06-25 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0006_alter_chart_chart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 25, 10, 23, 47, 921373)),
        ),
    ]
