# Generated by Django 5.2 on 2025-07-01 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0007_alter_chart_chart_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=datetime.datetime(2025, 7, 1, 7, 32, 56, 597394), help_text='Birth, holiday, marriage etc')),
                ('event_city', models.CharField(default='Ufa')),
                ('event_country', models.CharField(default='Russia')),
                ('transit_date', models.DateTimeField(default=None)),
                ('transit_city', models.CharField(default=None)),
                ('transit_country', models.CharField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 7, 32, 56, 597394)),
        ),
    ]
