# Generated by Django 5.2 on 2025-07-01 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0008_transitchart_alter_chart_chart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 9, 14, 58, 742667)),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 9, 14, 58, 742667), help_text='Birth, holiday, marriage etc'),
        ),
    ]
