# Generated by Django 5.2 on 2025-07-17 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0010_alter_chart_chart_date_alter_transitchart_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 7, 49, 18, 778635)),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 7, 49, 18, 778635), help_text='Birth, holiday, marriage etc'),
        ),
    ]
