# Generated by Django 5.2 on 2025-07-17 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0017_alter_chart_chart_date_alter_transitchart_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 8, 16, 4, 812954)),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 8, 16, 4, 812954), help_text='Birth, holiday, marriage etc'),
        ),
    ]
