# Generated by Django 5.2 on 2025-07-30 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0027_alter_chart_chart_date_alter_transitchart_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 7, 47, 52, 361611)),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 7, 47, 52, 361611), help_text='Birth, holiday, marriage etc'),
        ),
    ]
