# Generated by Django 5.2 on 2025-08-06 06:36

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0031_zodiacincolors_alter_chart_chart_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 6, 36, 18, 623705)),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='jup_symbol_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='mars_symbol_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='moon_symbol_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='neptune_symbol_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='pluto_symbol_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='saturn_symbol_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='sun_symbol_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='uranus_symbol_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='venus_symbol_s',
            field=models.IntegerField(),
        ),
    ]
