# Generated by Django 5.2 on 2025-08-11 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0032_alter_chart_chart_date_alter_transitchart_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitchart',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transitchart',
            name='transit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='chart_city',
            field=models.CharField(default='Ufa'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='chart_country',
            field=models.CharField(default='Russia'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='chart_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='degrees_ticks_color',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='degrees_track_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='jup_marker_c',
            field=models.CharField(default='royalblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='jup_symbol_s',
            field=models.IntegerField(verbose_name='12'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='jupiter_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='mars_marker_c',
            field=models.CharField(default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='mars_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='mars_symbol_s',
            field=models.IntegerField(verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='mercury_marker_c',
            field=models.CharField(default='grey', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='mercury_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='mercury_symbol_s',
            field=models.IntegerField(verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='moon_marker_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='moon_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='moon_symbol_s',
            field=models.IntegerField(verbose_name='9'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='neptune_marker_c',
            field=models.CharField(default='darkcyan', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='neptune_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='neptune_symbol_s',
            field=models.IntegerField(verbose_name='13'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='pluto_marker_c',
            field=models.CharField(default='firebrick', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='pluto_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='pluto_symbol_s',
            field=models.IntegerField(verbose_name='13'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='saturn_marker_c',
            field=models.CharField(default='darkslateblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='saturn_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='saturn_symbol_s',
            field=models.IntegerField(verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='sun_marker_c',
            field=models.CharField(default='gold', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='sun_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='sun_symbol_s',
            field=models.IntegerField(verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_aqua_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_aqua_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_aries_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_aries_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_aries_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_cancer_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_cancer_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_cancer_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_capricorn_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_capricorn_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_capricorn_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_gemini_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_gemini_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_gemini_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_leo_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_leo_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_leo_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_libra_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_libra_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_libra_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_pisces_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_pisces_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_pisces_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_sag_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_sag_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_sag_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_scorpio_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_scorpio_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_scorpio_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_taurus_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_taurus_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_taurus_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_virgo_axis_ec',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_virgo_axis_fc',
            field=models.CharField(default='#A800D8', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_virgo_axis_tc',
            field=models.CharField(default='#2BC200', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='uranus_marker_c',
            field=models.CharField(default='chartreuse', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='uranus_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='uranus_symbol_s',
            field=models.IntegerField(verbose_name='13'),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='venus_marker_c',
            field=models.CharField(default='pink', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='venus_symbol_c',
            field=models.CharField(default='aliceblue', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='venus_symbol_s',
            field=models.IntegerField(verbose_name='9'),
        ),
    ]
