# Generated by Django 5.2 on 2025-08-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0033_alter_transitchart_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiacincolors',
            name='jup_symbol_s',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='mars_symbol_s',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='mercury_symbol_s',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='moon_symbol_s',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='neptune_symbol_s',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='pluto_symbol_s',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='saturn_symbol_s',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='sun_symbol_s',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_aqua_axis_tc',
            field=models.CharField(default='hottpink', max_length=20),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='uranus_symbol_s',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='zodiacincolors',
            name='venus_symbol_s',
            field=models.IntegerField(default=9),
        ),
    ]
