# Generated by Django 5.2 on 2025-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0034_alter_zodiacincolors_jup_symbol_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiacincolors',
            name='track_aqua_axis_tc',
            field=models.CharField(default='hotpink', max_length=20),
        ),
    ]
