# Generated by Django 5.2 on 2025-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0035_alter_zodiacincolors_track_aqua_axis_tc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=20)),
                ('planet_deg', models.CharField(max_length=16)),
                ('planet_sign', models.CharField(max_length=16)),
            ],
        ),
    ]
