# Generated by Django 5.2 on 2025-08-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0036_planetdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanetData',
        ),
        migrations.AddField(
            model_name='chart',
            name='planet_deg',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='planet_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='chart',
            name='planet_sign',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
