# Generated by Django 5.2 on 2025-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0037_delete_planetdata_chart_planet_deg_chart_planet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='planet_deg',
            field=models.CharField(default='00.00', max_length=16),
        ),
    ]
