# Generated by Django 5.2 on 2025-08-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0038_alter_chart_planet_deg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='planet_deg',
            field=models.CharField(default='28.05', max_length=16),
        ),
        migrations.AlterField(
            model_name='chart',
            name='planet_name',
            field=models.CharField(default='Uranus', max_length=20),
        ),
        migrations.AlterField(
            model_name='chart',
            name='planet_sign',
            field=models.CharField(default='Aquarius', max_length=16),
        ),
    ]
