# Generated by Django 5.2 on 2025-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0039_alter_chart_planet_deg_alter_chart_planet_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='planet_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='planet_name',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='planet_sign',
        ),
        migrations.AddField(
            model_name='chart',
            name='Jupiter',
            field=models.CharField(default='5°37, Aquarius', max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='Mars',
            field=models.CharField(default='15°21, Scorpio', max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='Mercury',
            field=models.CharField(default='18°04, Aquarius', max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='Moon',
            field=models.CharField(default='14°44, Taurus', max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='Neptune',
            field=models.CharField(default='11°60, Sagittarius', max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='Pluto',
            field=models.CharField(default='13°40, Libra', max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='Saturn',
            field=models.CharField(default='15°18, Scorpio', max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='Sun',
            field=models.CharField(default='5°05, Aquarius', max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='Uranus',
            field=models.CharField(default='28°05, Scorpio', max_length=16),
        ),
        migrations.AddField(
            model_name='chart',
            name='Venus',
            field=models.CharField(default='12°05, Aquarius', max_length=16),
        ),
    ]