# Generated by Django 5.2 on 2025-08-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0041_remove_chart_jupiter_remove_chart_mars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_image',
            field=models.ImageField(default='static/plots/chart_for_date.png', upload_to='media/astroplan/images/'),
        ),
    ]
