# Generated by Django 5.2 on 2025-08-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0042_chart_chart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_image',
            field=models.ImageField(default='media/plots/chart_for_date.png', upload_to='media/astroplan/images/'),
        ),
    ]
