# Generated by Django 5.2 on 2025-08-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0044_alter_chart_chart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_image',
            field=models.ImageField(upload_to='chart_plots/'),
        ),
    ]
