# Generated by Django 5.2 on 2025-08-29 11:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0045_alter_chart_chart_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='Jupiter_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Jupiter_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Mars_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Mars_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Mercury_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Mercury_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Moon_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Moon_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Neptune_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Neptune_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Pluto_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Pluto_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Saturn_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Saturn_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Sun_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Sun_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Uranus_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Uranus_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Venus_deg',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='Venus_sign',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='chart_image',
        ),
        migrations.CreateModel(
            name='FullChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(default='Ufa')),
                ('country', models.CharField(default='Russia')),
                ('Sun_deg', models.CharField(default='5°05')),
                ('Sun_sign', models.CharField(default='Aquarius')),
                ('Moon_deg', models.CharField(default='14°44')),
                ('Moon_sign', models.CharField(default='Taurus')),
                ('Mercury_deg', models.CharField(default='18°04')),
                ('Mercury_sign', models.CharField(default='Aquarius')),
                ('Venus_deg', models.CharField(default='12°05')),
                ('Venus_sign', models.CharField(default='Aquarius')),
                ('Mars_deg', models.CharField(default='15°21')),
                ('Mars_sign', models.CharField(default='Scorpio')),
                ('Jupiter_deg', models.CharField(default='5°37')),
                ('Jupiter_sign', models.CharField(default='Aquarius')),
                ('Saturn_deg', models.CharField(default='15°18')),
                ('Saturn_sign', models.CharField(default='Scorpio')),
                ('Uranus_deg', models.CharField(default='28°05')),
                ('Uranus_sign', models.CharField(default='Scorpio')),
                ('Neptune_deg', models.CharField(default='11°60')),
                ('Neptune_sign', models.CharField(default='Sagittarius')),
                ('Pluto_deg', models.CharField(default='13°40, Libra')),
                ('Pluto_sign', models.CharField(default='Libra')),
                ('chart_image', models.ImageField(upload_to='chart_plots/')),
                ('drawer', models.ForeignKey(default='drawer', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
