# Generated by Django 5.2 on 2025-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0047_alter_fullchart_drawer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullchart',
            name='chart_name',
            field=models.CharField(default='My birthdate'),
        ),
    ]
