# Generated by Django 5.2 on 2025-09-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0054_transitfullchart_delete_transitfullchartform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullchart',
            name='drawer',
        ),
        migrations.RemoveField(
            model_name='transitfullchart',
            name='drawer',
        ),
        migrations.AddField(
            model_name='fullchart',
            name='drawer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transitfullchart',
            name='drawer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
