# Generated by Django 5.2 on 2025-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0055_remove_fullchart_drawer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_mode',
            field=models.CharField(choices=[(65536, 'Sidereal'), (0, 'Tropical'), (8, 'Heliocentric')], default='Sidereal'),
        ),
        migrations.AddField(
            model_name='chart',
            name='house_system',
            field=models.CharField(choices=[('P', 'Placidus'), ('R', 'Regiomontanus'), ('E', 'Equal'), ('Without houses', 'Without houses')], default='Without houses'),
        ),
    ]
