# Generated by Django 5.2 on 2025-11-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0057_fullchart_chart_mode_fullchart_house_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullchart',
            name='chart_name',
            field=models.CharField(default='Today'),
        ),
    ]
