# Generated by Django 5.2 on 2025-11-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0058_alter_fullchart_chart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitfullchart',
            name='ev_chart_mode',
            field=models.CharField(choices=[(65536, 'Sidereal'), (0, 'Tropical'), (8, 'Heliocentric')], default='Sidereal'),
        ),
        migrations.AddField(
            model_name='transitfullchart',
            name='ev_house_system',
            field=models.CharField(choices=[('P', 'Placidus'), ('R', 'Regiomontanus'), ('E', 'Equal'), ('Without houses', 'Without houses')], default='Without houses'),
        ),
        migrations.AddField(
            model_name='transitfullchart',
            name='tr_chart_mode',
            field=models.CharField(choices=[(65536, 'Sidereal'), (0, 'Tropical'), (8, 'Heliocentric')], default='Sidereal'),
        ),
        migrations.AddField(
            model_name='transitfullchart',
            name='tr_house_system',
            field=models.CharField(choices=[('P', 'Placidus'), ('R', 'Regiomontanus'), ('E', 'Equal'), ('Without houses', 'Without houses')], default='Without houses'),
        ),
    ]
