# Generated by Django 5.2 on 2025-11-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0059_transitfullchart_ev_chart_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitfullchart',
            name='ev_chart_mode',
            field=models.IntegerField(choices=[(65536, 'Sidereal'), (0, 'Tropical'), (8, 'Heliocentric')], default='Sidereal'),
        ),
        migrations.AlterField(
            model_name='transitfullchart',
            name='tr_chart_mode',
            field=models.IntegerField(choices=[(65536, 'Sidereal'), (0, 'Tropical'), (8, 'Heliocentric')], default='Sidereal'),
        ),
    ]
