# Generated by Django 5.2 on 2025-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0061_alter_chart_chart_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullchart',
            name='chart_mode',
            field=models.IntegerField(choices=[(65536, 'Sidereal'), (0, 'Tropical'), (8, 'Heliocentric')], default='Sidereal'),
        ),
    ]
