# Generated by Django 5.2 on 2025-11-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0062_alter_fullchart_chart_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitfullchart',
            name='transit_name',
            field=models.CharField(default='My enlightenment day'),
        ),
    ]
