# Generated by Django 5.2 on 2025-11-20 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0063_alter_transitfullchart_transit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneColorZodiacRingMF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chart_city', models.CharField(default='Ufa')),
                ('chart_country', models.CharField(default='Russia')),
                ('chart_mode', models.IntegerField(choices=[(65536, 'Sidereal'), (0, 'Tropical'), (8, 'Heliocentric')], default='Sidereal')),
                ('chart_house_system', models.CharField(choices=[('P', 'Placidus'), ('R', 'Regiomontanus'), ('E', 'Equal'), ('Without houses', 'Without houses')], default='Without houses')),
                ('face_color', models.CharField(default='#300c63')),
                ('edge_color', models.CharField(default='#3dffc8')),
                ('text_color', models.CharField(default='#3dffc8')),
                ('tick_color', models.CharField(default='#63ffd3')),
                ('deg_color', models.CharField(default='#63ffd3')),
                ('marker_color', models.CharField(default='#ffc83d')),
                ('symbol_color', models.CharField(default='#ff3d74')),
                ('house_ax_color', models.CharField(default='#ffc83d')),
                ('house_number_color', models.CharField(default='#ffc83d')),
                ('house_track_color', models.CharField(default='#ffc83d')),
                ('marker_size', models.IntegerField(default=25)),
                ('symbol_size', models.IntegerField(default=15)),
                ('font_size', models.IntegerField(default=50)),
                ('line_width', models.IntegerField(default=25)),
                ('house_ax_lw', models.IntegerField(default=3)),
                ('house_num_fs', models.IntegerField(default=27)),
                ('house_track_lw', models.IntegerField(default=3)),
            ],
        ),
    ]
