# Generated by Django 5.2 on 2025-11-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0064_onecolorzodiacringmf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneColorZodiacRingMF',
        ),
    ]
