# Generated by Django 5.2 on 2025-11-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0066_onecolorzodiacringmf'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecolorzodiacringmf',
            name='chart_name',
            field=models.CharField(default='Got the Olympic Prize'),
        ),
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='chart_image',
            field=models.ImageField(default='static/images/tr_one_clr.png', upload_to='chart_plots/'),
        ),
    ]
