# Generated by Django 5.2 on 2025-11-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroplan', '0067_onecolorzodiacringmf_chart_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onecolorzodiacringmf',
            name='line_width',
            field=models.IntegerField(default=3),
        ),
    ]
