
    server {
        listen 81;
        server_name 127.0.0.1 145.255.1.71;


       location /static/ {
            alias /var/www/staticfiles/;
       }

       location / {
            proxy_pass http://astro-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       }

    }
